version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:8000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
